language: ruby
rvm:
  - 1.9.3
  - 2.0.0

bundler_args: --without development

before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database timepulse_test;'

notifications:
  recipients
    - evan@lrdesign.com

